### ISSUE TITLE
Stake/Upstake nodes

### ISSUE THREAD

**Issue by slugo** [stake-igniter/mvp-igniter#16]
Tasks

- [x] stake-igniter/middleman-platform#18
- [x] stake-igniter/middleman-platform#19
- [ ] stake-igniter/mvp-igniter#5
- [ ] stake-igniter/mvp-igniter#4
