### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by slugo** [stake-igniter/mvp-igniter#17]
Tasks:

- [ ] stake-igniter/mvp-igniter#10
- [ ] stake-igniter/mvp-igniter#9
- [ ] stake-igniter/mvp-igniter#8
- [ ] stake-igniter/mvp-igniter#7
- [ ] stake-igniter/mvp-igniter#6
